config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :teachers
  resources :schools

end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :students
  has_many :teachers

  validates :name, presence: true

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :school
  belongs_to :teacher

  validates :name, presence: true
  validates :age, numericality: {
  only_integer: true,
  greater_than: 16
}
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :school
  has_many :students

  validates :name, presence: true
  validates :age, numericality: {
  only_integer: true,
  greater_than: 18
}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  def index
    @schools = School.all
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)

    if @school.save
      redirect_to school_path(@school.id), notice: "Success!"
    else
      flash[:alert] = "Error Occured! School couldn't be saved!"
      render :new
    end
  end

  def show # GET /schools/:id
    @school = School.find(params[:id])
  end

  private

  def school_params
    params.require(:school).permit(:id, :name, :motto, :location)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to school_path(@student.school_id), notice: "Success!"
    else
      flash[:alert] = "Error Occured! School couldn't be saved!"
      render :new
    end
  end
  
  private

  def student_params
    params.require(:student).permit(:id, :name, :age, :school_id, :teacher_id)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def index
    @teachers = Teacher.all
  end

  def show # GET /schools/:id
    @teacher = Teacher.find(params[:id])
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to school_path(@teacher.school_id), notice: "Success!"
    else
      flash[:alert] = "Error Occured! School couldn't be saved!"
      render :new
    end
  end

  private

  def teacher_params
    params.require(:teacher).permit(:id, :name, :age, :school_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecureSchool</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navigation-centered" role="banner">
    <div class="navigation-centered-wrapper">
      <a href="javascript:void(0)" class="mobile-logo">
        <img src="https://raw.githubusercontent.com/thoughtbot/empties/master/source/images/placeholder.png" alt="Logo image">
      </a>
      <a href="javascript:void(0)" id="js-navigation-centered-mobile-menu" class="navigation-centered-mobile-menu">Menu</a>
      <nav role="navigation">
        <ul id="js-navigation-centered-menu" class="navigation-centered-menu show">
          <li class="nav-link"><a href="javascript:void(0)">Menu1</a></li>
          <li class="nav-link"><a href="javascript:void(0)">Menu2</a></li>
          <li class="nav-link logo">
            <a href="javascript:void(0)" class="logo">
              <img src="https://raw.githubusercontent.com/thoughtbot/empties/master/source/images/placeholder.png" alt="Logo image">
            </a>
          </li>
          <li class="nav-link"><a href="javascript:void(0)">Menu3</a></li>
          <li class="nav-link"><a href="javascript:void(0)">Menu4</a></li>
        </ul>
      </nav>
    </div>
  </header>

<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<small>School Name: <%= f.text_field :name %> </small>
<small>School Motto: <%= f.text_field :motto %> </small>
<small>School Location: <%= f.text_field :location %> </small>
<p><%= f.submit :create %></p>

app/views/schools/index.html.erb
<body>

  <span id="school-index-display">
    <h1>Schools Dashboard</h1>
  </span>

  <section class="content-right">

    <aside>
      <div class='side-items'>
        <p class="read-more">Welcome Admin</p>
        <%= form_for(:school, :url => {:action => 'create'}) do |f| %>
          <% render(:partial => "form", :locals => {:f => f}) %>
        <% end %>
      </div>
    </aside>

    <article>
      <% @schools.each do |school| %>
        <%= link_to school_path(id: school.id), :class => 'button white' do %>
            <div class='items'>
              <h2>
                <%= school.name %>
                <small class="location"><%= school.location %></small>
              </h2>
              <p>School Motto: <%= school.motto %></p>
              <p>School ID: <%= school.id %></p>
              <p>Number of teachers: <%= school.teachers.count %></p>
              <p>Number of students: <%= school.students.count %></p>
            </div>
        <hr style='border: none;' />
        <% end %>
      <% end %>
    </article>

  </section>

</body>

app/views/schools/show.html.erb
<body>

  <span id="school-show-display">
    <h1><%= @school.name %></h1>
  </span>

  <span id="school-show-controls"></span>

  <section class="content-left">

    <div id="school-show-info">
      <article>
        <div class='items'>
          <p>School Motto: <%= @school.motto %></p>
          <p>School Location: <%= @school.location %></p>
        </div>
      </article>
      <aside>
        <div class='side-items'>
          <small>Welcome Admin</small>
          <p>Number of teachers: <%= @school.teachers.count %></p>
          <p>Number of students: <%= @school.students.count %></p>
        </div>
      </aside>
    </div>

    <div id="school-show-teachers">
      <article>
        <% @school.teachers.each do |teacher| %>
          <%= link_to teacher_path(teacher_id: teacher.id), :class => 'button white' do %>
            <div class='items'>
              <h2><%= teacher.name %></h2>
              <p>Age: <%= teacher.age %></p>
              <p>Teacher ID: <code><%= teacher.id %></code></p>
              <p>School ID: <code><%= teacher.school_id %></code></p>
            </div>
            <hr style='border: none;' />
          <% end %>
        <% end %>
      </article>
      <aside>
        <div class='side-items'>
          <small>Welcome Educator</small>
          <h2><%= link_to "Create new teacher", new_teacher_path(school_id: @school.id) %></h2>
        </div>
      </aside>
    </div>

    <div id="school-show-students">
      <article>
        <% @school.students.each do |student| %>
              <div class='items'>
                <h2><%= student.name %></h2>
                <p>Age: <%= student.age %></p>
                <p>Student ID: <code><%= student.id %></code></p>
                <p>School ID: <code><%= student.school_id %></code></p>
                <p>Teacher ID: <code><%= student.teacher_id %></code></p>
              </div>
          <hr style='border: none;' />
        <% end %>
      </article>
      <aside>
        <div class='side-items'>
          <small>Welcome Teacher</small>
          <h2><%= link_to "Create new student", new_student_path(school_id: @school.id) %></h2>
        </div>
      </aside>
    </div>

  </section>
</body>

app/views/students/_form.html.erb
<small>Student Name: <%= f.text_field :name %> </small>
<small>Student Age: <%= f.text_field :age %> </small>
<small>School ID: <%= f.text_field :school_id %> </small>
<small>Teacher ID: <%= f.text_field :teacher_id %> </small>
<p><%= f.submit :create %></p>

app/views/students/index.html.erb
<body>

  <span id="student-index-display">
    <h1>Students Dashboard</h1>
  </span>

  <section class="content-right">

    <aside>
      <div class='side-items'>
        <p class="read-more">Welcome Admin</p>
        <%= form_for(:student, :url => {:action => 'create'}) do |f| %>
          <% render(:partial => "form", :locals => {:f => f}) %>
        <% end %>
      </div>
    </aside>

    <article>
      <% @students.each do |student| %>
        <%= link_to student_path(id: student.id), :class => 'button white' do %>
          <div class='items'>
            <h2><%= student.name %></h2>
            <p>School: <%= student.school.name %></p>
            <p>Teacher Name: <%= student.teacher.name %></p>
            <p>Student Age: <%= student.age %></p>
            <p>Student ID: <%= student.id %></p>
          </div>
          <hr style='border: none;' />
        <% end %>
      <% end %>
    </article>

  </section>

</body>

app/views/students/new.html.erb
<h1>New Student!</h1>

<%= form_for @student do |f| %>
<p>Student Name: <%= f.text_field :name %> </p>
<p>Student Age: <%= f.text_field :age %> </p>
<p>School ID: <%= f.text_field :school_id %> </p>
<p>Teacher ID: <%= f.text_field :teacher_id %> </p>
<p><%= f.submit :create %></p>
<% end %>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

app/views/teachers/_form.html.erb
<small>Teacher Name: <%= f.text_field :name %> </small>
<small>Teacher Age: <%= f.text_field :age %> </small>
<small>School ID: <%= f.text_field :school_id %> </small>
<p><%= f.submit :create %></p>

app/views/teachers/index.html.erb
<body>

  <span id="teacher-index-display">
    <h1>Teachers Dashboard</h1>
  </span>

  <section class="content-right">

    <aside>
      <div class='side-items'>
        <p class="read-more">Welcome Admin</p>
        <%= form_for(:teacher, :url => {:action => 'create'}) do |f| %>
          <% render(:partial => "form", :locals => {:f => f}) %>
        <% end %>
      </div>
    </aside>

    <article>
      <% @teachers.each do |teacher| %>
        <%= link_to teacher_path(id: teacher.id), :class => 'button white' do %>
          <div class='items'>
            <h2><%= teacher.name %></h2>
            <p>School: <%= teacher.school.name %></p>
            <p>Teacher Age: <%= teacher.age %></p>
            <p>Teacher ID: <%= teacher.id %></p>
          </div>
          <hr style='border: none;' />
        <% end %>
      <% end %>
    </article>

  </section>

</body>

app/views/teachers/new.html.erb
<h1>New Teacher!</h1>

<%= form_for @teacher do |f| %>
<p>Teacher Name: <%= f.text_field :name %> </p>
<p>Teacher Age: <%= f.text_field :age %> </p>
<p>School ID: <%= f.text_field :school_id %> </p>
<p><%= f.submit :create %></p>
<% end %>

app/views/teachers/show.html.erb
<body>

  <span id="teacher-show-display">
    <h1><%= @teacher.name %></h1>
  </span>

  <section class="content-left">

    <div id="teacher-show-students">
      <article>
        <% @teacher.students.each do |student| %>
              <div class='items'>
                <h2><%= student.name %></h2>
                <p>Age: <%= student.age %></p>
                <p>Student ID: <code><%= student.id %></code></p>
                <p>School ID: <code><%= student.school_id %></code></p>
              </div>
          <hr style='border: none;' />
        <% end %>
      </article>
      <aside>
        <div class='side-items'>
          <small>Welcome Professor!</small>
          <p>Number of students: <%= @teacher.students.count %></p>
        </div>
      </aside>
    </div>

  </section>

</body>